server:
  port: 8002
  tomcat:
    min-spare-threads: 20 #初始化线程是20
    max-threads: 100 #最大线程数是100
    # 超时时间
    connection-timeout: 5000

spring:
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB
  application:
    name: recharge
  aop:
    auto: true
    proxy-target-class: false
  redis:
    host: 47.103.74.81
    port: 6379
    password:
    database: 0

  datasource:
    url: jdbc:mysql://47.103.74.81:3306/wsgs?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    # 使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      validation-query: select 1

mybatis:
  typeAliasesPackage: cn.xds.recharge.dto
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    cn.xds.recharge: debug

wx:
  appid: wx29c49905292b67dd
  secret: 009025655e21909d94a3dfb123607609
  lang: zh_CN
  grant_type: authorization_code
  getAccessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token
  getInfoUrl: https://api.weixin.qq.com/cgi-bin/user/info

sms:
  product: Dysmsapi
  domain: dysmsapi.aliyuncs.com
  accessKeyId: LTAI4FpKGd84SPLBLKseEyqZ
  accessKeySecret: ga6gY5E5tFYQvE3Ft4Svpl12Wmj7bQ
  signName: 行东上
  templateCode: SMS_175690135

channel:
 key: df41bbb9ee213bdb0e46c2021e572fb392a2a2ce0df5e168422c8a486d62ee29
 account: 990
 queryBalanceURL: http://39.108.59.67:8160/unicomAync/queryBalance.do
 rechargeURL: http://39.108.59.67:8160/telephone/buy.do

