server:
  port: 8002
  tomcat:
    min-spare-threads: 20 #初始化线程是20
    max-threads: 100 #最大线程数是100
    # 超时时间
    connection-timeout: 5000

spring:
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB
  application:
    name: recharge
  aop:
    auto: true
    proxy-target-class: false

  datasource:
    url: jdbc:mysql://47.103.74.81:3306/wsgs?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    # 使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      validation-query: select 1

mybatis:
  typeAliasesPackage: cn.xds.recharge.model
  mapperLocations: classpath:mapper/**/*.xml

logging:
  level:
    cn.xds.recharge: debug

wx:
  appid: wx29c49905292b67dd
  secret: 009025655e21909d94a3dfb123607609
  grant_type: authorization_code
  getAccessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token


redis:
  host: 47.103.74.81
  port: 6379
  password:
  database: 0